name: yolov4-deepsort

dependencies:
  - python==3.9
  - pip
  - matplotlib
  - opencv
  - pip:
    - opencv-python
    - lxml
    - tqdm
    - tensorflow==2.10.0
    - absl-py
    - easydict
    - pillow